<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<NoWarn>$(NoWarn);NU1701</NoWarn>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>MeshEditor.Forms</RootNamespace>
		<AssemblyName>MeshEditor.Forms</AssemblyName>
		<LangVersion>latest</LangVersion>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AssetTargetFallback>$(AssetTargetFallback);net48;net472;net471;net461;net452;net45;net40;net35;net20</AssetTargetFallback>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<WarningLevel>4</WarningLevel>
		<Prefer32Bit>false</Prefer32Bit>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
		<DefineConstants>TRACE</DefineConstants>
		<WarningLevel>4</WarningLevel>
		<Prefer32Bit>false</Prefer32Bit>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
		<DefineConstants>TRACE</DefineConstants>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MeshEditor.Common\MeshEditor.Common.csproj" />
		<ProjectReference Include="..\MeshEditor.Core\MeshEditor.Core.csproj" />
	</ItemGroup>
</Project>
