using System;
using System.Collections.Generic;
using System.Text;
using MeshEditor.Data;
using MeshEditor.CoreInterface;
using System.IO;
using OpenTK.Mathematics;
using System.Diagnostics;
using System.Reflection;

namespace MeshEditor.IO
{
	public class GiDMshFileFormatSaver : IMeshSaver
	{

		private delegate T Transformation<T>(T arg);

		#region Fields, constructor

		private TextWriter output;
		private Dictionary<ElementType, SortedDictionary<int, Node>> nodeMap;
		private Dictionary<ElementType, SortedDictionary<int, Element>> elementMap;
		private MeshIOEventArgs ioea;

        private int allEntitiesToWriteCount;

		#endregion

		#region IMeshSaver Members

		public void SaveMesh(Mesh mesh, string filename, bool saveWithoutCuttedElements, YesNoQuestion cancelled)
		{
			ioea = new MeshIOEventArgs(0, "Saving mesh", null);
			generateMaps(mesh, saveWithoutCuttedElements);

            Transformation<Vector3> coordinateTransformer = delegate(Vector3 pos)
            {
                return (pos / mesh.ResizeFactor) + mesh.PositionOffset;
            };

            writeMeshToFile(filename, mesh.Name, coordinateTransformer, cancelled);
		}
		
		public void SaveMesh(IMeshFileParser fileParser, string destination, YesNoQuestion cancelled)
		{
			Debug.Assert(fileParser != null && !string.IsNullOrEmpty(destination));
			ioea = new MeshIOEventArgs(0, "Saving mesh", null);
			generateMaps(fileParser);
			string meshName = Path.GetFileNameWithoutExtension(fileParser.Filename);

			writeMeshToFile(destination, meshName, /*coordinateTransformer: */ null, cancelled);
		}

		#endregion

		#region IProgressNotifier Members

		public event MeshIOEventHandler Step;

		#endregion

        #region Private methods

        private void writeMeshToFile(string filename, string meshName, Transformation<Vector3> coordinateTransformer, YesNoQuestion cancelled)
        {
            using (output = new StreamWriter(filename))
            {
                int itemIndex = 0, itemsToWrite = this.allEntitiesToWriteCount;

				// write header
				output.WriteLine(GiDMshFileFormatParser.COMMENT_PATTERN + " GiD Post Results File 1.0");				
				output.WriteLine(string.Format("{0} Generated by {1} version {2}", GiDMshFileFormatParser.COMMENT_PATTERN, Utilities.Functions.GetAssemblyTitle(), Utilities.Functions.GetAssemblyVersion()));

                foreach (ElementType elementType in elementMap.Keys)
                {
                    output.WriteLine();

                    // MESH "mesh_name" dimension my_dimension Elemtype my_type Nnode my_number
					const int dimension = 3; // always three dimensions // Element.GetDimensionOfElementType(elementType);
					int nodeNumber = Element.MapElementTypeToNodeCount(elementType);
					output.WriteLine(string.Format("{0} \"{1}\" {2} {3} {4} {5} {6} {7}", GiDMshFileFormatParser.MESH_PATTERN, meshName + "_" + elementType, GiDMshFileFormatParser.DIMENSION_PATTERN, dimension, GiDMshFileFormatParser.ELEMTYPE_PATTERN, getNameOfElementType(elementType), GiDMshFileFormatParser.NNODE_PATTERN, nodeNumber));
                    output.WriteLine();

					output.WriteLine(GiDMshFileFormatParser.COORDINATES_PATTERN);
                    // # node number   coordinate_x  coordinate_y  coordinate_z
                    foreach (Node node in nodeMap[elementType].Values)
                    {
                        Vector3 transformedPosition = (coordinateTransformer != null) ? coordinateTransformer(node.Position) : node.Position;
                        output.WriteLine(string.Format("{0} {1} {2} {3}", node.ID, transformedPosition.X.ToString(CultureProvider.EnglishCulture), transformedPosition.Y.ToString(CultureProvider.EnglishCulture), transformedPosition.Z.ToString(CultureProvider.EnglishCulture)));

                        if (Step != null) // inform about progress
                        {
                            int percent = (int)((float)itemIndex / (float)itemsToWrite * 100f);
                            if (ioea.PercentDone != percent)
                            {
                                if (cancelled != null && cancelled())
                                    return;
                                ioea.PercentDone = percent;
                                Step(this, ioea);
                            }
                        }
                        itemIndex++;
                    }
					output.WriteLine(GiDMshFileFormatParser.END_PATTERN + " " + GiDMshFileFormatParser.COORDINATES_PATTERN);

                    output.WriteLine();

                    output.WriteLine(GiDMshFileFormatParser.ELEMENTS_PATTERN);
                    // # element  node_1   node_2  node_3 material_number
                    foreach (Element element in elementMap[elementType].Values)
                    {
                        writeElement(element);

                        if (Step != null) // inform about progress
                        {
                            int percent = (int)((float)itemIndex / (float)itemsToWrite * 100f);
                            if (ioea.PercentDone != percent)
                            {
                                if (cancelled != null && cancelled())
                                    return;
                                ioea.PercentDone = percent;
                                Step(this, ioea);
                            }
                        }
                        itemIndex++;
                    }
                    output.WriteLine(GiDMshFileFormatParser.END_PATTERN + " " + GiDMshFileFormatParser.ELEMENTS_PATTERN);
                }
            }
        }

        private string getNameOfElementType(ElementType elementType)
        {
			string name;
			if (!GiDMshFileFormatParser.NamesOfElementTypes.TryGetValue(elementType, out name))
				throw new NotSupportedException(elementType.ToString() + " element type is not supported.");
			return name;
        }

		private void writeElement(Element element)
		{
			// # el_num node_1 node_2 node_3 material
			StringBuilder text = new StringBuilder();
			text.Append(element.ID + " ");
			foreach (Node node in element.IterateThroughAllNodesIncludingEdgeMiddleNodes())
				text.Append(node.ID.ToString() + " ");
			text.Append(element.Property);
			output.WriteLine(text.ToString());
		}

		private void generateMaps(Mesh mesh, bool saveWithoutHiddenElements)
		{
			this.nodeMap = new Dictionary<ElementType, SortedDictionary<int, Node>>();
			this.elementMap = new Dictionary<ElementType, SortedDictionary<int, Element>>();
            this.allEntitiesToWriteCount = 0;

			foreach (Element e in mesh.Elements)
			{
				// pokud se uklada uriznuta sit, tak zkontrolovatm, jestli tento prvek neni v seznamu uriznutych...
				if (saveWithoutHiddenElements && mesh.HiddenElements.Contains(e))
					continue;
				SortedDictionary<int, Element> elements;
				if (!elementMap.TryGetValue(e.ElementType, out elements))
					elements = elementMap[e.ElementType] = new SortedDictionary<int, Element>();				
				elements[e.ID] = e;
                allEntitiesToWriteCount++;
			}

			foreach (ElementType elementType in elementMap.Keys)
			{
				foreach (Element element in elementMap[elementType].Values)
				{
					SortedDictionary<int, Node> nodes;
					if (!nodeMap.TryGetValue(element.ElementType, out nodes))
						nodes = nodeMap[element.ElementType] = new SortedDictionary<int, Node>();
					foreach (Node n in element.IterateThroughAllNodesIncludingEdgeMiddleNodes())
					{
						if (!isPresentInNodeMap(n.ID))
						{
							allEntitiesToWriteCount++;
							nodes[n.ID] = n;
						}
					}
				}
			}
		}

		private void generateMaps(IMeshFileParser fileParser)
        {
			this.nodeMap = new Dictionary<ElementType, SortedDictionary<int, Node>>();
			this.elementMap = new Dictionary<ElementType, SortedDictionary<int, Element>>();
			this.allEntitiesToWriteCount = 0;

			Dictionary<int, Node> nodeIDs = new Dictionary<int, Node>();

			foreach (Node n in fileParser.ReadNodes())
				nodeIDs[n.ID] = n;

			foreach (ElementDraft ed in fileParser.ReadElements())
			{
				Element e = createElementFrom(ed, nodeIDs);
				SortedDictionary<int, Element> elements;
				if (!elementMap.TryGetValue(e.ElementType, out elements))
					elements = elementMap[e.ElementType] = new SortedDictionary<int, Element>();
				elements[e.ID] = e;
				allEntitiesToWriteCount++;
			}

			foreach (ElementType elementType in elementMap.Keys)
			{
				foreach (Element element in elementMap[elementType].Values)
				{
					SortedDictionary<int, Node> nodes;
					if (!nodeMap.TryGetValue(element.ElementType, out nodes))
						nodes = nodeMap[element.ElementType] = new SortedDictionary<int, Node>();
					foreach (Node n in element.IterateThroughAllNodesIncludingEdgeMiddleNodes())
					{
						if (!isPresentInNodeMap(n.ID))
						{
							allEntitiesToWriteCount++;
							nodes[n.ID] = n;
						}
					}
				}
			}
        }

		private bool isPresentInNodeMap(int nodeID)
		{
			if (nodeMap == null)
				return false;
			foreach (ElementType elementType in nodeMap.Keys)
			{
				if (nodeMap[elementType].ContainsKey(nodeID))
					return true;
			}
			return false;
		}

		private Element createElementFrom(ElementDraft draft, Dictionary<int, Node> nodeIDs)
		{
			Element newElement;

			//ApproximationType approxType = Element.GetApproximationTypeFrom(draft.Type);
			ElementType elementType = draft.Type;
			Node[] nodesOfElement = new Node[draft.NodeIDs.Length];

			for (int i = 0; i < nodesOfElement.Length; i++)
			{
				Node n;
				if (nodeIDs.TryGetValue(draft.NodeIDs[i], out n))
					nodesOfElement[i] = n;
				else
					throw new MeshSavingException("Node " + draft.NodeIDs[i] + " in element " + draft.ID + " was not defined.");
			}

			switch (draft.Type)
			{
				case ElementType.BeamLinear:
					newElement = new Beam(draft.ID, elementType, nodesOfElement[0], nodesOfElement[1]);
					break;
				case ElementType.BeamQuadratic:
					newElement = new QuadraticBeam(draft.ID, elementType, nodesOfElement[0], nodesOfElement[1], nodesOfElement[2]);
					break;
				case ElementType.TriangleLinear:
				case ElementType.TriangleQuadratic:
					newElement = new Triangle(draft.ID, elementType, nodesOfElement[0], nodesOfElement[1], nodesOfElement[2]);
					break;
				case ElementType.QuadLinear:
				case ElementType.QuadQuadratic:
					newElement = new Quadrilateral(draft.ID, elementType, nodesOfElement[0], nodesOfElement[1], nodesOfElement[2], nodesOfElement[3]);
					break;
				case ElementType.TetrahedronLinear:
				case ElementType.TetrahedronQuadratic:
					newElement = new Tetrahedron(draft.ID, elementType, nodesOfElement); break;
				case ElementType.SquarePyramidLinear:
				case ElementType.SquarePyramidQuadratic:
					newElement = new Pyramid(draft.ID, elementType, nodesOfElement); break;
				case ElementType.TriangularPrismLinear:
				case ElementType.TriangularPrismQuadratic:
					newElement = new Wedge(draft.ID, elementType, nodesOfElement); break;
				case ElementType.HexahedronLinear:
				case ElementType.HexahedronQuadratic:
					newElement = new Hexahedron(draft.ID, elementType, nodesOfElement); break;
				default:
					throw new ArgumentException("This argument is not supported.", "draft.Type");
			}
			// set property of new element
			newElement.Property = draft.Property;

			return newElement;
		}

		#endregion

	}
}
